version: '3.1'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    image: slurm.controller
    container_name: controller
    privileged: true
    volumes:
      - ./storage:/home
      - ./secret:/.secret
    restart: always
    hostname: balthasar.magi
    networks:
      - slurm_d
    environment:
      CLUSTER_NAME: magi
      CONTROL_MACHINE: balthasar
      COMPUTE_NODES: worker01 worker02 worker03
      PARTITION_NAME: docker



  worker01:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: slurm.worker
    container_name: worker01
    privileged: true
    volumes:
      - ./storage:/home
      - ./secret:/.secret
    restart: always
    hostname: casper01.magi
    networks:
      - slurm_d
    environment:
      CONTROL_MACHINE: balthasar
      COMPUTE_NODES: worker01 worker02 worker03

  worker02:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: slurm.worker
    container_name: worker02
    privileged: true
    volumes:
      - ./storage:/home
      - ./secret:/.secret
    restart: always
    hostname: casper02.magi
    networks:
      - slurm_d
    environment:
      CONTROL_MACHINE: balthasar
      COMPUTE_NODES: worker01 worker02 worker03

  worker03:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: slurm.worker
    container_name: worker03
    privileged: true
    volumes:
      - ./storage:/home
      - ./secret:/.secret
    restart: always
    hostname: casper03.magi
    networks:
      - slurm_d
    environment:
      CONTROL_MACHINE: balthasar
      COMPUTE_NODES: worker01 worker02 worker03
  
networks:
  slurm_d: